sonar.projectKey=student-api
sonar.projectName=Student API
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,tests/**

sonar.tests=tests
sonar.test.inclusions=tests/**/*.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=sqp_d94b3847425cb23102f2e368f532b226eba7cd8d
